### ISSUE TITLE
Auto re-equip after mining?

### ISSUE THREAD

**Issue by adrnde** [teelolws/UnderlightAnglerAuto#5]
Addon works fine, but if you mine or herb an underwater node, you have to manually drag pole out of tool slot and put back to re-acquire fish form.

Is there some script or macro command to accomplish that, ie, trigger the two functions in this addon manually?

Thanks.

**Comment by teelolws** [comment]
Hmm. There might be a way. Unfortunately, I don't have a character with mining or herbalism and underlight angler to try and find a solution.

I'll do some poking around on the PTR when I have a chance and get back to you.

**Comment by teelolws** [comment]
Okay, this works on the 10.1.5 PTR and should work here too. Addon will now watch for "You receive loot: Stranglekelp" type messages and reequip the underlight angler if appropriate.
