### ISSUE TITLE
Cancel "Fishing For Attention" buff after being out of water for x seconds?

### ISSUE THREAD

**Issue by muiqo** [teelolws/UnderlightAnglerAuto#8]
Thanks for maintaining your addon, its such on awesome QoL feature!!

Would it be possible to have an option to automatically cancel the "Fishing For Attention" buff after being out of the water for x amount of seconds?  Tho i love my underlight angler, i'd rather see my mog after using it 😅

**Comment by teelolws** [comment]
What if you just turn off the profession equipment mog? Have a chat with this NPC:
![image](https://github.com/user-attachments/assets/213dd3f1-1c94-4a28-ac70-6c2c97a1da64)

Turn it off with:
![image](https://github.com/user-attachments/assets/f89c195c-c4e6-464f-93d5-a6c629cedce0)

**Comment by muiqo** [comment]
I have that turned off, the idea was to restore the weapon-transmog after being done with swimming :) Or maybe just cancel the buff after mounting!? Just an idea, keep up the great work!

**Comment by teelolws** [comment]
Ok so cancelling it when you're out of water is out: the buff is required to get the water walking, and I have no way to detect if you're on land or water walking. I can only tell "swimming" vs "not swimming".

I'll cancel it when you mount, as long as the buff was gained via this addon. If you're already mounted when you gained the buff, it will cancel when you dismount. If you're in combat when you mount/dismount, it cannot cancel the buff and will discard future attempts.

**Comment by muiqo** [comment]
Thanks for implementing it! I totally forgot about the water-walking ability since i am playing priest and use levitate for that.

Had a peek at the code to test it in a Weakaura to cancel the buff if not swimming, checking `MOUNT_JOURNAL_USABILITY_CHANGED` is so clever! Thanks again for your work <3
